version: '3.8'

services:
  # 后端Python Flask服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
      - /app/__pycache__
    command: python start_app.py

  # Redis缓存
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data_test:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data_test: 