global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'divine-friend-frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: /metrics

  - job_name: 'divine-friend-backend'
    static_configs:
      - targets: ['backend:80']
    metrics_path: /wp-json/zen/metrics/v1/prometheus

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']